remote_theme: "mmistakes/minimal-mistakes@4.28.0"

plugins:
  - jekyll-include-cache
# Site settings
title: "Sam Bowyer"
name: "Sam Bowyer"
description: "GIS Analyst | Marine & Offshore Spatial Planning"
url: "https://sambowyergis.com"

# Author profile (shows in sidebar)
author:
  name: "Sam Bowyer"
  bio: "Final year Geography BSc at the University of St Andrews, specialising in GIS and marine spatial planning."
  location: "Scotland, UK"
  email: "sam@sambowyergis.com"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/sam-bowyer-b2707a26b"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sambowyergis"

# Remove the recent posts from homepage
paginate: 0
include: 
  - _pages
favicon:
  - rel: "shortcut icon"
    type: "image/png"
    href: "/assets/images/favicon.png"
minimal_mistakes_skin: "dark"
