remote_theme: "mmistakes/minimal-mistakes@4.28.0"

plugins:
  - jekyll-include-cache
# Site settings
title: " "
logo: "/assets/images/favicon.png"
name: "Sam Bowyer"
description: "Student GIS Analyst | Marine & Offshore Spatial Planning"
url: "https://sambowyergis.com"

# Author profile (shows in sidebar)
author:
  name: "Sam Bowyer"
  bio: "Penultimate year Geography BSc at the University of St Andrews, specialising in GIS and marine spatial planning."
  location: "St Andrews, Scotland"
  email: "sam@sambowyergis.com"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/sam-bowyer-b2707a26b"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sambowyergis"
    - label: "School of Geography"
      icon: "fas fa-fw fa-university"
      url: "https://www.st-andrews.ac.uk/geography-sustainable-development/"

# Remove the recent posts from homepage
paginate: 0
include: 
  - _pages

minimal_mistakes_skin: "dark"
