remote_theme: "mmistakes/minimal-mistakes@4.28.0"

plugins:
  - jekyll-include-cache
# Site settings
title: "Sam Bowyer"
name: "Sam Bowyer"
description: "GIS Analyst | Marine & Offshore Spatial Planning"
url: "https://sambowyergis.com"

# Author profile (shows in sidebar)
author:
  name: "Sam Bowyer"
  bio: "Final year Geography BSc at the University of St Andrews, specialising in GIS and marine spatial planning."
  location: "Scotland, UK"
  email: "sam@sambowyergis.com"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.linkedin.com%2Fin%2Fsam-bowyer-b2707a26b%3Futm_source%3Dshare_via%26utm_content%3Dprofile%26utm_medium%3Dmember_ios&data=05%7C02%7Csb443%40st-andrews.ac.uk%7C8b074df3c8404078101608de8f1ad30f%7Cf85626cb0da849d3aa5864ef678ef01a%7C0%7C0%7C639105542555272685%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=435tVp64nk7F1Y%2FkeaSLwShh1Vnhd%2FoTsfQWqvSgIOg%3D&reserved=0"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sambowyergis"

# Remove the recent posts from homepage
paginate: 0
